FROM node:12.19-slim

ENV USER=dcbell

# install python and make
RUN apt-get update && \
	apt-get install -y python3 build-essential && \
	apt-get purge -y --auto-remove
	
# create dcbell user
RUN groupadd -r ${USER} && \
	useradd --create-home --home /home/dcbell -r -g ${USER} ${USER}
	
# set up volume and user
USER ${USER}
WORKDIR /home/dcbell

COPY package*.json ./
RUN npm install
VOLUME [ "/home/dcbell" ]

COPY . .

ENTRYPOINT [ "node", "index.js" ]